/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <windows.h>
#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

BOOL __fastcall _raise_securityfailure(struct _EXCEPTION_POINTERS *ExceptionInfo);
void __cdecl __noreturn _report_gsfailure(uintptr_t StackCookie);
BOOL _report_rangecheckfailure();
BOOL __fastcall _report_securityfailure(unsigned int a1);
BOOL __fastcall _report_securityfailureEx(unsigned int a1, unsigned int a2, __int64 a3);
struct _IMAGE_RUNTIME_FUNCTION_ENTRY *__fastcall capture_current_context(PCONTEXT ContextRecord);
struct _IMAGE_RUNTIME_FUNCTION_ENTRY *__fastcall capture_previous_context(PCONTEXT ContextRecord);
// void __stdcall RtlCaptureContext(PCONTEXT ContextRecord);
// PRUNTIME_FUNCTION __stdcall RtlLookupFunctionEntry(ULONG64 ControlPc, PULONG64 ImageBase, PUNWIND_HISTORY_TABLE HistoryTable);
// PEXCEPTION_ROUTINE __stdcall RtlVirtualUnwind(ULONG HandlerType, ULONG64 ImageBase, ULONG64 ControlPc, PRUNTIME_FUNCTION FunctionEntry, PCONTEXT ContextRecord, PVOID *HandlerData, PULONG64 EstablisherFrame, PKNONVOLATILE_CONTEXT_POINTERS ContextPointers);
// LONG __stdcall UnhandledExceptionFilter(struct _EXCEPTION_POINTERS *ExceptionInfo);
// LPTOP_LEVEL_EXCEPTION_FILTER __stdcall SetUnhandledExceptionFilter(LPTOP_LEVEL_EXCEPTION_FILTER lpTopLevelExceptionFilter);
// HANDLE __stdcall GetCurrentProcess();
// BOOL __stdcall TerminateProcess(HANDLE hProcess, UINT uExitCode);
// BOOL __stdcall IsProcessorFeaturePresent(DWORD ProcessorFeature);

//-------------------------------------------------------------------------
// Data declarations

int volmd; // weak
int dword_4; // weak
__int64 qword_10; // weak
int dword_18; // weak
_QWORD qword_20[16]; // weak
_CONTEXT GS_ContextRecord; // idb
const struct _EXCEPTION_POINTERS GS_ExceptionPointers = { &volmd, &GS_ContextRecord }; // idb


//----- (0000000000000580) ----------------------------------------------------
BOOL __fastcall _raise_securityfailure(struct _EXCEPTION_POINTERS *ExceptionInfo)
{
  HANDLE CurrentProcess; // rax

  SetUnhandledExceptionFilter(0i64);
  UnhandledExceptionFilter(ExceptionInfo);
  CurrentProcess = GetCurrentProcess();
  return TerminateProcess(CurrentProcess, 0xC0000409);
}

//----- (00000000000005B8) ----------------------------------------------------
void __cdecl __noreturn _report_gsfailure(uintptr_t StackCookie)
{
  DWORD64 retaddr; // [rsp+38h] [rbp+0h]
  DWORD64 v2; // [rsp+40h] [rbp+8h] BYREF

  v2 = StackCookie;
  if ( IsProcessorFeaturePresent(0x17u) )
    __fastfail(2u);
  capture_previous_context(&GS_ContextRecord);
  GS_ContextRecord.Rip = retaddr;
  GS_ContextRecord.Rsp = (DWORD64)&v2;
  qword_10 = retaddr;
  GS_ContextRecord.Rcx = v2;
  volmd = -1073740791;
  dword_4 = 1;
  dword_18 = 1;
  unk_20 = 2i64;
  _raise_securityfailure((struct _EXCEPTION_POINTERS *)&GS_ExceptionPointers);
}
// 0: using guessed type int volmd;
// 4: using guessed type int dword_4;
// 10: using guessed type __int64 qword_10;
// 18: using guessed type int dword_18;

//----- (0000000000000690) ----------------------------------------------------
BOOL _report_rangecheckfailure()
{
  return _report_securityfailure(8u);
}

//----- (00000000000006A8) ----------------------------------------------------
BOOL __fastcall _report_securityfailure(unsigned int a1)
{
  DWORD64 retaddr; // [rsp+28h] [rbp+0h]
  unsigned int v3; // [rsp+30h] [rbp+8h] BYREF

  v3 = a1;
  if ( IsProcessorFeaturePresent(0x17u) )
    __fastfail(v3);
  capture_current_context(&GS_ContextRecord);
  GS_ContextRecord.Rip = retaddr;
  GS_ContextRecord.Rsp = (DWORD64)&v3;
  qword_10 = retaddr;
  volmd = -1073740791;
  dword_4 = 1;
  dword_18 = 1;
  unk_20 = v3;
  return _raise_securityfailure((struct _EXCEPTION_POINTERS *)&GS_ExceptionPointers);
}
// 0: using guessed type int volmd;
// 4: using guessed type int dword_4;
// 10: using guessed type __int64 qword_10;
// 18: using guessed type int dword_18;

//----- (0000000000000748) ----------------------------------------------------
BOOL __fastcall _report_securityfailureEx(unsigned int a1, unsigned int a2, __int64 a3)
{
  unsigned int i; // [rsp+20h] [rbp-18h]
  DWORD64 retaddr; // [rsp+38h] [rbp+0h]
  unsigned int v6; // [rsp+40h] [rbp+8h] BYREF
  unsigned int v7; // [rsp+48h] [rbp+10h]
  __int64 v8; // [rsp+50h] [rbp+18h]

  v8 = a3;
  v7 = a2;
  v6 = a1;
  if ( IsProcessorFeaturePresent(0x17u) )
    __fastfail(v6);
  capture_current_context(&GS_ContextRecord);
  GS_ContextRecord.Rip = retaddr;
  GS_ContextRecord.Rsp = (DWORD64)&v6;
  qword_10 = retaddr;
  volmd = -1073740791;
  dword_4 = 1;
  if ( v7 && !v8 )
    v7 = 0;
  if ( v7 > 0xE )
    --v7;
  dword_18 = v7 + 1;
  qword_20[0] = v6;
  for ( i = 0; i < v7; ++i )
    qword_20[i + 1] = *(_QWORD *)(v8 + 8i64 * i);
  return _raise_securityfailure((struct _EXCEPTION_POINTERS *)&GS_ExceptionPointers);
}
// 0: using guessed type int volmd;
// 4: using guessed type int dword_4;
// 10: using guessed type __int64 qword_10;
// 18: using guessed type int dword_18;
// 20: using guessed type _QWORD qword_20[16];

//----- (0000000000000858) ----------------------------------------------------
struct _IMAGE_RUNTIME_FUNCTION_ENTRY *__fastcall capture_current_context(PCONTEXT ContextRecord)
{
  DWORD64 Rip; // rdi
  struct _IMAGE_RUNTIME_FUNCTION_ENTRY *result; // rax
  unsigned __int64 ImageBase; // [rsp+50h] [rbp+8h] BYREF
  unsigned __int64 EstablisherFrame; // [rsp+58h] [rbp+10h] BYREF
  PVOID HandlerData; // [rsp+60h] [rbp+18h] BYREF

  RtlCaptureContext(ContextRecord);
  Rip = ContextRecord->Rip;
  result = RtlLookupFunctionEntry(Rip, &ImageBase, 0i64);
  if ( result )
    return (struct _IMAGE_RUNTIME_FUNCTION_ENTRY *)RtlVirtualUnwind(
                                                     0,
                                                     ImageBase,
                                                     Rip,
                                                     result,
                                                     ContextRecord,
                                                     &HandlerData,
                                                     &EstablisherFrame,
                                                     0i64);
  return result;
}

//----- (00000000000008C8) ----------------------------------------------------
struct _IMAGE_RUNTIME_FUNCTION_ENTRY *__fastcall capture_previous_context(PCONTEXT ContextRecord)
{
  DWORD64 Rip; // rsi
  int i; // edi
  struct _IMAGE_RUNTIME_FUNCTION_ENTRY *result; // rax
  unsigned __int64 ImageBase; // [rsp+60h] [rbp+8h] BYREF
  unsigned __int64 EstablisherFrame; // [rsp+68h] [rbp+10h] BYREF
  PVOID HandlerData; // [rsp+70h] [rbp+18h] BYREF

  RtlCaptureContext(ContextRecord);
  Rip = ContextRecord->Rip;
  for ( i = 0; i < 2; ++i )
  {
    result = RtlLookupFunctionEntry(Rip, &ImageBase, 0i64);
    if ( !result )
      break;
    result = (struct _IMAGE_RUNTIME_FUNCTION_ENTRY *)RtlVirtualUnwind(
                                                       0,
                                                       ImageBase,
                                                       Rip,
                                                       result,
                                                       ContextRecord,
                                                       &HandlerData,
                                                       &EstablisherFrame,
                                                       0i64);
  }
  return result;
}

// nfuncs=7 queued=7 decompiled=7 lumina nreq=0 worse=0 better=0
// ALL OK, 7 function(s) have been successfully decompiled
