/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall _GSHandlerCheck_SEH_noexcept(__int64 a1, __int64 a2, __int64 a3);
// __int64 terminate(void); weak
// __int64 _current_exception(void); weak
// __int64 _current_exception_context(void); weak
// __int64 _GSHandlerCheck_SEH(void); weak


//----- (0000000000000000) ----------------------------------------------------
__int64 __fastcall _GSHandlerCheck_SEH_noexcept(__int64 a1, __int64 a2, __int64 a3)
{
  __int64 result; // rax

  result = _GSHandlerCheck_SEH();
  if ( (*(_BYTE *)(a1 + 4) & 0x66) == 0 && *(_DWORD *)a1 == -529697949 && (_DWORD)result == 1 )
  {
    *(_QWORD *)_current_exception() = a1;
    *(_QWORD *)_current_exception_context() = a3;
    terminate();
    __debugbreak();
  }
  return result;
}
// 70: using guessed type __int64 terminate(void);
// 78: using guessed type __int64 _current_exception(void);
// 80: using guessed type __int64 _current_exception_context(void);
// 88: using guessed type __int64 _GSHandlerCheck_SEH(void);

// nfuncs=5 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
