/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: Visual C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 __fastcall _GSHandlerCheck_EH(__int64 a1, __int64 a2, __int64 a3, __int64 a4);
// __int64 __fastcall _GSHandlerCheckCommon(_QWORD, _QWORD, _QWORD); weak
// __int64 __fastcall _CxxFrameHandler3(_QWORD, _QWORD, _QWORD, _QWORD); weak


//----- (0000000000000000) ----------------------------------------------------
__int64 __fastcall _GSHandlerCheck_EH(__int64 a1, __int64 a2, __int64 a3, __int64 a4)
{
  __int64 v4; // rbx
  __int64 result; // rax

  v4 = *(_QWORD *)(a4 + 56);
  _GSHandlerCheckCommon(a2, a4, v4 + 4);
  result = 1i64;
  if ( ((((*(_DWORD *)(a1 + 4) & 0x66) != 0) + 1) & *(_DWORD *)(v4 + 4)) != 0 )
    return _CxxFrameHandler3(a1, a2, a3, a4);
  return result;
}
// B0: using guessed type __int64 __fastcall _GSHandlerCheckCommon(_QWORD, _QWORD, _QWORD);
// B8: using guessed type __int64 __fastcall _CxxFrameHandler3(_QWORD, _QWORD, _QWORD, _QWORD);

// nfuncs=3 queued=1 decompiled=1 lumina nreq=0 worse=0 better=0
// ALL OK, 1 function(s) have been successfully decompiled
